### PR TITLE
Removed non-translated strings

### PR DESCRIPTION
**Pull request by Aga-C**
First of the series, and also the largest one. I'll gradually send PRs to other apps.

### CODE REVIEW

**Comment by naveensingh** [comment]
@Aga-C I removed the strings in all other projects. Let me know if you find any problems. Thanks

**Comment by Aga-C** [comment]
@naveensingh You mistakenly removed some valid strings, e.g. https://github.com/FossifyOrg/Gallery/commit/248569e47f510c94786d81369c0718678264e7a3#diff-13d3ddb353c4952c9bb458c38901937286cfeac021f043f99d44d81e93f2e2c9L44.

**Comment by naveensingh** [comment]
Right, I'll fix that now.

**Comment by Aga-C** [comment]
@naveensingh Also, I've found non-translated plural forms and faq_1_title: https://github.com/FossifyOrg/Music-Player/commit/851caf7f9e8719f9e6f0856ec64f5df833f0a111#diff-d430adea2ba1ea4aa238130a7fc2fdb5f4eee93cc75974270ebcc3e8269dc9f2.

**Comment by naveensingh** [comment]
Yes, I see them too. I'll remove those now...

**Comment by Aga-C** [comment]
Here, only plural forms: https://github.com/FossifyOrg/Clock/commit/edf3e91ebbcf466dc8ffce1fbe8fad71a44258ed#diff-7b00a236bb4a8a0b9240042a06942d302211460e8614354b6d396f6ed475cc48.

**Comment by Aga-C** [comment]
And, I hope it's the last thing - in Gallery English strings have been added to many languages, probably because of `\?`.

**Pull request merged**
