### PR TITLE
Make EditText.highlightText faster by adding spans directly

### PR DESCRIPTION
**Pull request by tom93**
This makes searching in medium/large texts (e.g. files opened in the File Editor) faster by orders of magnitude, especially when there are many matches. Tested on Android 9 and 14 with a 100KB text file (but the speed difference should also be noticeable on smaller files).

From the commit message:

> The previous code called setText() after adding each span, which is very slow when there is a lot of text. It is enough to call setText() once at the end if any matches were found.
> 
> But we can do even better: we can add the highlighting spans directly to the existing Editable of the EditText, and skip setText() entirely, thus avoiding any copying of the text.
> 
> The documentation of EditText.getText() says "The content of the return value should not be modified. If you want a modifiable one, you should make your own copy first." (inherited from TextView), but adding spans to the return value appears to work fine.

### CODE REVIEW

**Comment by naveensingh** [comment]
I tried using a 200KB text file and got a crash, I guess the File editor could use some work.

**Comment by tom93** [comment]
Ha ha, I can open a 1MB text file on a Android-x86 9 VM with 2GB RAM, but it does increase resident RAM usage by a whopping 200MB (217MB when idle, 418MB with file open).

Thanks for merging!

**Comment by naveensingh** [comment]
Seems to work fine, thanks!

**Comment by tom93** [comment]
Thanks! (I misread the earlier merge commit and said my first thanks too soon. I swear I wasn't trying to be passive-aggressive!)

**Comment by naveensingh** [comment]
@tom93 I figured, don't worry about it :)

**Comment by naveensingh** [comment]
> I can open a 1MB text file on an Android-x86 9 VM with 2GB RAM

By the way, when fixing bugs or implementing features, please try to test things on real devices with average specs or emulators (if possible).

**Pull request merged**
