### PR TITLE
Use format `yyyyMMdd_HHmmss` for current date

### PR DESCRIPTION
**Pull request by MrChocolatine**
#### What is it?
- [ ] Bugfix
- [X] Feature
- [x] Codebase improvement

#### Description of the changes in your PR

Use format `yyyyMMdd_HHmmss` for current date.

This change is a partial effort towards:
- https://github.com/FossifyOrg/Contacts/issues/89
- FossifyOrg/General-Discussion#129

#### Fixes the following issue(s)
Prefix issues with "Fixes FossifyOrg/AppRepo" so that GitHub closes them when this PR is merged (note that each "Fixes #" should be in its own item). For Commons, it should always be in a format like "Fixes FossifyOrg/AppRepo#123" -->
- Fixes FossifyOrg/General-Discussion/issues/129

#### Acknowledgement
- [x] I read the [contribution guidelines](https://github.com/FossifyOrg/Commons/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by MrChocolatine** [comment]
Hello

**Comment by naveensingh** [comment]
Thanks but you shouldn't work on an issue until `needs triage` label is removed. It may not always get accepted.

**Comment by RustoMCSpit** [comment]
hi all, why was a format without distinction between datapoints selected? i use the 2025_01_15_14_43_23 as thats what the voice recorder has shipped for years now.

**Comment by RustoMCSpit** [comment]
```
    val simpleDateFormat = 
SimpleDateFormat("yyyyMMdd_HHmmss", 
Locale.getDefault())
```

```
    val separatedDateFormat = 
SimpleDateFormat("yyyy_MM_dd_HH_mm_ss", 
Locale.getDefault())
```

**Pull request merged**
